kind: Deployment
apiVersion: apps/v1
metadata:
  name: dep1
spec:
  selector:
    matchLabels:
      name: pradeep
  replicas: 3
  template:
    metadata:
      name: pod
      labels:
        name: pradeep
    spec:
      containers:
      - name: cont
        image: pradeepcoeb/javapradeep:27
        ports:
        - containerPort: 80
